version: '3'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"  # WebDriver port
      - "7900:7900"  # noVNC port for debugging (optional)
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - START_XVFB=true
    volumes:
      - /dev/shm:/dev/shm  # Shared memory for better performance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped